// Code generated by proto-gen-deepcopy. DO NOT EDIT.
// source: github.com/vine-io/raft/examples/proto/hello.proto

package pb

import (
	v1 "github.com/vine-io/apimachinery/apis/meta/v1"
	runtime "github.com/vine-io/apimachinery/runtime"
)

func init() {
	sets = append(sets,
		&Epoch{},
		&EpochList{},
		&Product{},
		&ProductList{},
	)
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Frame) DeepCopyInto(out *Frame) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Epoch) DeepCopyInto(out *Epoch) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*Epoch)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from Epoch.
func (in *Epoch) DeepFromObject(src runtime.Object) {
	o := src.(*Epoch)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new Epoch.
func (in *Epoch) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Epoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *EpochList) DeepCopyInto(out *EpochList) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
	{
		in, out := &in.ListMeta, &out.ListMeta
		out = new(v1.ListMeta)
		(*in).DeepCopyInto(out)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*Epoch, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Epoch)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*EpochList)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from EpochList.
func (in *EpochList) DeepFromObject(src runtime.Object) {
	o := src.(*EpochList)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new EpochList.
func (in *EpochList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(EpochList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Product) DeepCopyInto(out *Product) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*Product)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from Product.
func (in *Product) DeepFromObject(src runtime.Object) {
	o := src.(*Product)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new Product.
func (in *Product) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Product)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *ProductList) DeepCopyInto(out *ProductList) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
	{
		in, out := &in.ListMeta, &out.ListMeta
		out = new(v1.ListMeta)
		(*in).DeepCopyInto(out)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*Product, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Product)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*ProductList)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from ProductList.
func (in *ProductList) DeepFromObject(src runtime.Object) {
	o := src.(*ProductList)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new ProductList.
func (in *ProductList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ProductList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *SnapshotMarshaller) DeepCopyInto(out *SnapshotMarshaller) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]*Product, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Product)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *GetProductRequest) DeepCopyInto(out *GetProductRequest) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *GetProductResponse) DeepCopyInto(out *GetProductResponse) {
	*out = *in
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(Product)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *CreateProductRequest) DeepCopyInto(out *CreateProductRequest) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *CreateProductResponse) DeepCopyInto(out *CreateProductResponse) {
	*out = *in
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(Product)
		(*in).DeepCopyInto(*out)
	}
}
