// Code generated by proto-gen-deepcopy. DO NOT EDIT.
// source: github.com/vine-io/raft/example/proto/hello.proto

package pb

import (
	v1 "github.com/vine-io/apimachinery/apis/meta/v1"
	runtime "github.com/vine-io/apimachinery/runtime"
)

func init() {
	sets = append(sets,
		&Epoch{},
		&Product{},
	)
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Frame) DeepCopyInto(out *Frame) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Epoch) DeepCopyInto(out *Epoch) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*Epoch)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from Epoch.
func (in *Epoch) DeepFrom(src runtime.Object) {
	o := src.(*Epoch)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new Epoch.
func (in *Epoch) DeepCopy() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Epoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Product) DeepCopyInto(out *Product) {
	*out = *in
	{
		in, out := &in.TypeMeta, &out.TypeMeta
		out = new(v1.TypeMeta)
		(*in).DeepCopyInto(out)
	}
}

// assert to App implement to runtime.Object
var _ runtime.Object = (*Product)(nil)

// DeepFrom is an auto-generated deepcopy function, copying value from Product.
func (in *Product) DeepFrom(src runtime.Object) {
	o := src.(*Product)
	o.DeepCopyInto(in)
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new Product.
func (in *Product) DeepCopy() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Product)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *SnapshotMarshaller) DeepCopyInto(out *SnapshotMarshaller) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]*Product, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Product)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *GetProductRequest) DeepCopyInto(out *GetProductRequest) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *GetProductResponse) DeepCopyInto(out *GetProductResponse) {
	*out = *in
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(Product)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *CreateProductRequest) DeepCopyInto(out *CreateProductRequest) {
	*out = *in
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *CreateProductResponse) DeepCopyInto(out *CreateProductResponse) {
	*out = *in
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(Product)
		(*in).DeepCopyInto(*out)
	}
}
