// Code generated by proto-gen-dao.

package pb

import (
	"github.com/vine-io/apimachinery/runtime"
	"github.com/vine-io/apimachinery/schema"
	apistorage "github.com/vine-io/apimachinery/storage"
	"gorm.io/gorm"
)

// GroupName is the group name for this API
const GroupName = ""

// SchemeGroupVersion is group version used to register these objects
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}

var (
	SchemaBuilder = runtime.NewSchemeBuilder(addKnownTypes)
	AddToScheme   = SchemaBuilder.AddToScheme
	sets          = make([]runtime.Object, 0)
)

var (
	FactoryBuilder = apistorage.NewFactoryBuilder(addKnownFactory)
	AddToBuilder   = FactoryBuilder.AddToFactory
	storageSet     = make([]apistorage.Storage, 0)
)

func addKnownFactory(db *gorm.DB, f apistorage.Factory) error {
	return f.AddKnownStorages(db, SchemeGroupVersion, storageSet...)
}

func addKnownTypes(scheme runtime.Scheme) error {
	return scheme.AddKnownTypes(SchemeGroupVersion, sets...)
}
