// Code generated by proto-gen-dao.

package pb

import (
	"github.com/vine-io/apimachinery/runtime"
	"github.com/vine-io/apimachinery/schema"
	apistorage "github.com/vine-io/apimachinery/storage"
)

// GroupName is the group name for this API
const GroupName = ""

// SchemeGroupVersion is group version used to register these objects
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}

var (
	FactoryBuilder = apistorage.NewFactoryBuilder(addKnownStorages)
	store          = make(map[schema.GroupVersionKind]apistorage.Storage)
	AddToFactory   = FactoryBuilder.AddToFactory
	SchemaBuilder  = runtime.NewSchemeBuilder(addKnownTypes)
	AddToScheme    = SchemaBuilder.AddToScheme
	sets           = make([]runtime.Object, 0)
)

func addKnownTypes(scheme runtime.Scheme) error {
	return scheme.AddKnownTypes(SchemeGroupVersion, sets...)
}

func addKnownStorages(factory apistorage.Factory) error {
	for k, v := range store {
		if err := factory.AddKnownStorage(k, v); err != nil {
			return nil
		}
	}
	return nil
}
